language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyouridea-gaston-nodejs
  api_key:
    secure: xw612FdkQTpxB5IMOWiYjV1yJFkbGTb9mQqNWncFFjWZutYKLwuO5nMdPRKUeV9UwDAQqxE8Myf7v+t4AE2LEwsmT4sEywZsjaelE/qUrMtHT5G7DOkp63AtEczrgkxC/IAsR70DAzq+t22CslidLav0cZz9LvUkoQd07f8Of+eJnMMCjWwuDs9ObdAInmh2zG9PBk7JvbAW84Q+TjsTLanF+xwYHP7sSO4qZGry1mhXRi1FAqCYbjBX9ODhyeAejE+0s8UX25FgWDywctlLRyo5o0P2Yvc8QLHSXs6W2lvbXpM9Q0Cx0LwkfhcYuV37571DHMmruhC0OAFotw/NdRIsakS7Fp3V/9+lex3aJglo11Vpk42o67aGhlRvfLBbVnMUJkWrzhvB6xkjjZvsAzgsHM8GznYxKXsPx+yYJ/dyattIpD7e+o0PqQdb7aER5PU0o2cnMdozq4PvBQ/Qad8cTqH4CsW0mcptaUk9Yre9mVU8Nfu0vQTABEgkBRD01sfS6pFVhjTcg6+s6p+IhhXHzHRBsETmsc57H3UMLg44alPy4+aNi5vP4UYfFOibS+XSs8+O/5F/8YL6tMn3EwCaO42ZaWV5h5zEWFKvkhTGXe00ZpJOQdJ8w4606clpREWJ9HcLwtZBQmxYDlEZjgcPt1iytoSVEYxPuqwoqbE=
